apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:       
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: "Exists"
      effect: "NoSchedule"
    - key: node-role.kubernetes.io/master
      operator: "Exists"
      effect: "NoSchedule"     
  containers:
  - image: httpd:2.4.41-alpine
    name: pod1-container
    resources: {}
status: {}
