apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virt-pvc
  namespace: virtualizacao
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: virt
      context: atividade
