apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: processor
  namespace: virtualizacao
rules:
- apiGroups: [""]
  resources: ["secrets", "configmap"]
  verbs: ["create"]
