apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: processor
  namespace: virtualizacao
roleRef:
  apiGroup: ""
  kind: Role
  name: processor
subjects:
- kind: ServiceAccount
  name: processor
  apiGroup: ""
